namespace: etcd

stack:
  defines: process-group
  runnable-list:
    - etcd/etcd1
    - etcd/etcd2
    - etcd/etcd3
  variables:
    monk_etcd1_port:
      type: int
      value: 2391
    monk_etcd2_port:
      type: int
      value: 2392
    monk_etcd3_port:
      type: int
      value: 2393
    monk_etcd_debug:
      env: ETCD_DEBUG
      type: bool
      value: false