---
namespace: etcd

stack:
  defines: process-group
  metadata:
    name: etcd
    description: |
      etcd is a distributed reliable key-value store for the most critical data of a distributed system, with a focus on being:

          Simple: well-defined, user-facing API (gRPC)
          Secure: automatic TLS with optional client cert authentication
          Fast: benchmarked 10,000 writes/sec
          Reliable: properly distributed using Raft

      etcd is written in Go and uses the Raft consensus algorithm to manage a highly-available replicated log.

      etcd is used in production by many companies, and the development team stands behind it in critical deployment scenarios, where etcd is frequently teamed with applications such as Kubernetes, locksmith, vulcand, Doorman, and many others. Reliability is further ensured by rigorous robustness testing.
    website: https://etcd.io/
    publisher: monk.io
    source: https://github.com/etcd-io/etcd
    icon: https://github.com/etcd-io/etcd/raw/main/logos/etcd-horizontal-color.svg
    tags: reliability, high availability, microservices, configuration management, scalability, service discovery, key-value store, security, coordination, performance, open source
    private: true
  runnable-list:
    - etcd/etcd1
    - etcd/etcd2
    - etcd/etcd3
  variables:
    monk_etcd1_port:
      type: int
      value: 2391
    monk_etcd2_port:
      type: int
      value: 2392
    monk_etcd3_port:
      type: int
      value: 2393
    monk_etcd_debug:
      env: ETCD_DEBUG
      type: bool
      value: false
